name: Compile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3
    - name: Install LaTeX dependencies
      run: make deps
    - name: Compile LaTeX document
      run: make
    - name: Upload PDF file
      uses: actions/upload-artifact@v3
      with:
        name: PDF
        path: paper.pdf
