name: Compile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3
    - name: Compile LaTeX to PDF
      uses: xu-cheng/latex-action@v3
      with:
        root_file: paper.tex
        extra_system_packages: "poppler-utils"
        post_compile: |
          set -x &&
          pdftops paper.pdf paper.ps &&
          gs -sDEVICE=pdfwrite -dBATCH -dNOPAUSE -dSAFER -sColorConversionStrategy=UseDeviceIndependentColor -dEmbedAllFonts=true -dPrinted=true -dPDFA -sProcessColorModel=DeviceRGB -dPDFACompatibilityPolicy=1 -dDetectDuplicateImages -r150 -dFastWebView=true -sOutputFile=paper_a.pdf paper.ps &&
          ls
      env:
        TEXINPUTS: ".:./styles/:"
        BSTINPUTS: ".:./styles/:"
    - name: Upload PDF file
      uses: actions/upload-artifact@v3
      with:
        name: PDF
        path: paper.pdf
    - name: Upload PDF-A file
      uses: actions/upload-artifact@v3
      with:
        name: PDF-A
        path: paper_a.pdf