name: Health

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3
    - name: Lint LaTeX document
      uses: ChiefGokhlayeh/textidote-action@v5
      id: lint
      with:
          root_file: paper.tex
          args: --check en --dict .vscode/ltex.dictionary.en-US.txt --read-all
    - name: Upload TeXtidote report
      uses: actions/upload-artifact@v2
      with:
          name: textidote_report
          path: report.html
    - name: Throw error if linter warnings exist
      if: ${{ steps.lint.outputs.num_warnings != 0 }}
      run: 'echo "::error file=main.tex::num_warnings: ${{ steps.lint.outputs.num_warnings }}"; exit 1;'
